routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/logout','Auth\LoginController@logout')->name('logout');
Auth::routes();

Route::get('/', 'HomeController@index')->name('home');


Route::middleware('auth')->group(function(){

    Route::resource('/panel/page','Panel\BerichtController');
    Route::resource('/panel/user','Panel\GebruikerController');

});


Route::get('/page','BerichtController@index')->name('page.index');
Route::get('/page/{title}', 'BerichtController@show')->name('page.show');
Route::get('/page/header/{id}','BerichtController@header')->name('page.header');

resources/views/includes/header.blade.php
<header>
    @include('includes.nav')
</header>

resources/views/includes/nav.blade.php
<nav class="m-l-15 m-t-15">
    <a href="{{ route('page.index') }}">Home</a>
    @guest
        <a class="m-r-15" style="float:right;" href="{{ route('login') }}">Login</a>
    @endguest
    @auth
        <a class="m-r-15" style="float:right;" href="{{ route('logout') }}">Uitloggen</a>
        <a class="m-r-15" style="float: right;" href="{{ route('page.create') }}">Maak nieuwe blog</a>
        <a class="m-r-15" style="float: right;" href="{{ route('user.create') }}">Maak nieuwe gebruiker</a>
        <a class="m-r-15" style="float: right;" href="{{ route('user.index') }}">Gebruikers</a>
    @endauth
</nav>