routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/logout','Auth\LoginController@logout')->name('logout');
Auth::routes();

Route::get('/', 'HomeController@index')->name('home');


Route::middleware('auth')->group(function(){

    Route::resource('/panel/page','Panel\BerichtController');
    Route::resource('/panel/user','Panel\GebruikerController');

});


Route::get('/page','BerichtController@index')->name('page.index');
Route::get('/page/{title}', 'BerichtController@show')->name('page.show');
Route::get('/page/header/{id}','BerichtController@header')->name('page.header');

resources/views/pages/pages/index.blade.php
@extends('layouts.app')

@section('title','ExamenBlog - Overzicht')

@section('content')
    @foreach($berichten as $bericht)
        <div class="post m-l-15 m-t-15 m-r-15">
            <h1>{{ $bericht->titel }}</h1>
            <p>Gemaakt op: {{ $bericht->created_at->format('d-m-Y') }}</p>
            <p><a href="{{ route('page.show',$bericht->titel) }}">Bezoek pagina</a></p>
            @auth
                <p><a href="{{ route('page.edit',$bericht->id) }}">Bewerk pagina</a></p>
            @endauth
        </div>
    @endforeach
@endsection

resources/views/pages/pages/page.blade.php
@extends('layouts.app')

@section('title', "ExmamenBlog - ".$bericht->title)

@section('content')
    <div class="post m-l-15 m-t-15 m-r-15">
        @if(!is_null($bericht->header))
        <div class="col-lg-12">
            <img class="header" src="{{ route('page.header',$bericht->header->id) }}" alt="">
        </div>
        @endif
        <h1>{{ $bericht->titel }}</h1>
        <div class="m-t-15">
            <p>{{ $bericht->content }}</p>
        </div>
        <p>Gemaakt op: {{ $bericht->created_at->format('d-m-Y') }}</p>
        @auth
            <p><a href="{{ route('page.edit',$bericht->id) }}">Bewerk pagina</a></p>
        @endauth
    </div>
@endsection