routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/logout','Auth\LoginController@logout')->name('logout');
Auth::routes();

Route::get('/', 'HomeController@index')->name('home');


Route::middleware('auth')->group(function(){

    Route::resource('/panel/page','Panel\BerichtController');
    Route::resource('/panel/user','Panel\GebruikerController');

});


Route::get('/page','BerichtController@index')->name('page.index');
Route::get('/page/{title}', 'BerichtController@show')->name('page.show');
Route::get('/page/header/{id}','BerichtController@header')->name('page.header');

app/Http/Controllers/Panel/BerichtController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Bericht;
use App\Http\Handlers\BerichtHandler;
use App\Http\Handlers\PhotoHandler;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class BerichtController extends Controller
{
    //
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $berichten = Bericht::all();

        return view('pages.pages.index',compact('berichten'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        if(!BerichtHandler::checkTitleAvailable($request->input('titel'))) {
            $bericht = BerichtHandler::store($request->all());
            if($request->hasFile('header')){
                $photoHandler = new PhotoHandler();
                $path = $photoHandler->store($bericht, $request->file('header'));
            }
        }else{
            $old = $request->all();
            $old['error'] = 'Titel bestaat al!';
            return redirect()->back()->withInput($old);
        }

        return redirect()->route('page.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($title)
    {
        //
        $bericht = BerichtHandler::show($title);

        return view('pages.pages.page',compact('bericht'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $bericht = Bericht::find($id);

        return view('panel.pages.edit',compact('bericht'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('panel.pages.create');
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */


    public function update(Request $request, $id)
    {
        //
        $bericht = Bericht::find($id);

        if($request->input('titel') != $bericht->titel){
            if(BerichtHandler::checkTitleAvailable($request->input('titel'))){
                $input = $request->all();
                $input['error'] = "Titel is al in gebruik!";
                return redirect()->back()->withInput($input);
            }
        }

        BerichtHandler::update($bericht, $request->all());

        return redirect()->route('page.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        Bericht::find($id)->delete();

        return redirect()->route('page.index');
    }
}

app/Http/Controllers/Panel/GebruikerController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Http\Handlers\GebruikerHandler;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class GebruikerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $users = User::where('id','!=',Auth::id())->get();

        return view('panel.users.index',compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('panel.users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        if(GebruikerHandler::checkEmailUnique($request->input('email'))){
            $input = $request->all();
            $input['error'] = 'Email bestaat al!';
            return redirect()->back()->withInput($input);
        }

        GebruikerHandler::store($request->all());

        return redirect()->route('user.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $user = User::find($id);

        return view('panel.users.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $user = User::find($id);

        $update_user = $request->all();

        if($user->email != $update_user['email']){
            if(GebruikerHandler::checkEmailUnique($update_user['email'])){
                $update_user['error'] = "Email bestaat al!";
                return redirect()->back()->withInput($update_user);
            }
        }

        if($request->input('password') == ""){
            unset($update_user['password']);
        }else{
            $update_user['password'] = bcrypt($request->input('password'));
        }
        GebruikerHandler::update($user, $update_user);

        return redirect()->route('user.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        User::find($id)->delete();

        return redirect()->route('user.index');
    }
}

app/Http/Controllers/Panel/PanelController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Http\Handlers\BerichtHandler;
use App\Http\Handlers\GebruikerHandler;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PanelController extends Controller
{
    //
    public function validateTitle(Request $request){
        return response()->json(BerichtHandler::checkTitleAvailable($request->input('title')));
    }

    public function validateEmail(Request $request){

        return response()->json(GebruikerHandler::checkEmailUnique($request->input('email')));

    }
}

resources/views/panel/pages/create.blade.php
@extends('layouts.app')

@section('title','ExamenBlog - Nieuw bericht')

@section('content')
    <div class="m-l-15 m-r-15">
        <h1>Nieuwe pagina</h1>
        <a href="{{ route('page.index') }}">Ga terug</a>
        <div class="panel p-t-15">
            @if(old('error'))
                <div class="alert alert-danger">{{ old('error') }}</div>
            @endif
            <form action="{{ route('page.store') }}" method="post" enctype="multipart/form-data">
                <div class="form-group col-lg-12 newRow">
                    <div class="col-lg-4 col-lg-push-4">
                        <label class="control-label" for="title">Titel</label>
                        <input class="form-control checkTitle" name="titel" type="text" id="title" placeholder="titel" value="{{ old('titel') }}">
                        <p id="error"></p>
                    </div>
                </div>
                <div class="form-group col-lg-12 newRow">
                    <div class="col-lg-4 col-lg-push-4">
                        <label class="control-label" for="content">Content</label>
                        <textarea name="content" class="form-control" id="content" cols="30" rows="10">{{ old('content') }}</textarea>
                    </div>
                </div>
                <div class="form-group col-lg-12 newRow">
                    <div class="col-lg-4 col-lg-push-4">
                        <label class="control-label" for="images">Afbeeldingen</label>
                        <input name="header" class="form-control" id="images" type="file" accept="image/*"/>
                    </div>
                </div>
                <div class="form-group col-lg-12 newRow">
                    <div class="col-lg-4 col-lg-push-4">
                        <input style="float: right;" class="button" type="submit" value="Maak aan">
                    </div>
                </div>
                {{ @csrf_field() }}
            </form>

            <div class="clearfix"></div>
        </div>
    </div>
    <script>
        var title = "";
    </script>
@endsection

resources/views/panel/pages/edit.blade.php
@extends('layouts.app')

@section('title','ExamenBlog - Nieuw bericht')

@section('content')
    <div class="m-l-15 m-r-15">
        <h1>{{ $bericht->titel }}</h1>
        <a href="{{ route('page.index') }}">Ga terug</a>
        <div class="panel p-t-15">
            @if(old('error'))
                <div class="alert alert-danger">{{ old('error') }}</div>
            @endif
            <form action="{{ route('page.update', $bericht->id) }}" method="post">
                <div class="form-group col-lg-12 newRow">
                    <div class="col-lg-4 col-lg-push-4">
                        <label class="control-label" for="title">Titel</label>
                        <input class="form-control checkTitle" name="titel" type="text" id="title" placeholder="titel" value="{{ $bericht->titel }}">
                        <p id="error"></p>
                    </div>
                </div>
                <div class="form-group col-lg-12 newRow">
                    <div class="col-lg-4 col-lg-push-4">
                        <label class="control-label" for="content">Content</label>
                        <textarea name="content" name="content" class="form-control" id="content" cols="30" rows="10">{{ $bericht->content }}</textarea>
                    </div>
                </div>
                <div class="form-group col-lg-12 newRow">
                    <div class="col-lg-4 col-lg-push-4">
                        <input style="float: right;" class="button" type="submit" value="Bewerk">
                    </div>
                </div>
                <input type="hidden" name="_method" value="patch">
                {{ @csrf_field() }}
            </form>
                <form action="{{ route('page.destroy',$bericht->id) }}" method="post">
                    <div class="form-group col-lg-12 newRow">
                        <div class="col-lg-4 col-lg-push-4">
                            <input type="submit" style="float: right;" value="Verwijder">
                            {{ @csrf_field() }}
                            <input type="hidden" name="_method" value="DELETE">
                        </div>
                    </div>
                </form>

            <div class="clearfix"></div>
        </div>
    </div>
    <script>
        var title = "{{ $bericht->titel }}";
    </script>
@endsection